-- 由 `DroneServer.exe --sql` (或 python run_server.py --sql) 依 ORM 定義產生,請勿手改。
-- 與原 EF Core 版結構相同;後端啟動時也會自動建立缺少的資料表。

BEGIN;

CREATE TABLE IF NOT EXISTS drones (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	serial_number VARCHAR(50) NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	model VARCHAR(50) NOT NULL, 
	status INTEGER NOT NULL, 
	battery_percent NUMERIC(5, 2) NOT NULL, 
	latitude DOUBLE PRECISION NOT NULL, 
	longitude DOUBLE PRECISION NOT NULL, 
	altitude_m DOUBLE PRECISION NOT NULL, 
	speed_mps DOUBLE PRECISION NOT NULL, 
	heading_deg DOUBLE PRECISION NOT NULL, 
	firmware_version VARCHAR(30) NOT NULL, 
	battery_capacity_wh NUMERIC(8, 2) NOT NULL, 
	max_speed_mps NUMERIC(6, 2) NOT NULL, 
	max_flight_minutes INTEGER NOT NULL, 
	home_latitude DOUBLE PRECISION NOT NULL, 
	home_longitude DOUBLE PRECISION NOT NULL, 
	total_flight_seconds BIGINT NOT NULL, 
	total_energy_wh NUMERIC(12, 2) NOT NULL, 
	last_heartbeat_at TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_drones_serial_number" ON drones (serial_number);

CREATE TABLE IF NOT EXISTS flight_routes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	name VARCHAR(80) NOT NULL, 
	description VARCHAR(300), 
	status INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	total_distance_m DOUBLE PRECISION NOT NULL, 
	estimated_minutes INTEGER NOT NULL, 
	estimated_energy_wh NUMERIC(8, 2) NOT NULL, 
	created_by INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS login_logs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	user_id INTEGER, 
	username VARCHAR(50) NOT NULL, 
	ip_address VARCHAR(64) NOT NULL, 
	user_agent VARCHAR(300), 
	is_success BOOLEAN NOT NULL, 
	fail_reason VARCHAR(100), 
	logged_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS "IX_login_logs_logged_at" ON login_logs (logged_at);

CREATE TABLE IF NOT EXISTS map_points (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	name VARCHAR(50) NOT NULL, 
	point_type INTEGER NOT NULL, 
	latitude DOUBLE PRECISION NOT NULL, 
	longitude DOUBLE PRECISION NOT NULL, 
	altitude_m DOUBLE PRECISION NOT NULL, 
	description VARCHAR(200), 
	created_by INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS menu_items (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	parent_id INTEGER, 
	key VARCHAR(50) NOT NULL, 
	title VARCHAR(50) NOT NULL, 
	icon VARCHAR(50) NOT NULL, 
	path VARCHAR(120) NOT NULL, 
	sort_order INTEGER NOT NULL, 
	permission_code VARCHAR(80), 
	is_visible BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES menu_items (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_menu_items_key" ON menu_items (key);
CREATE INDEX IF NOT EXISTS "IX_menu_items_parent_id" ON menu_items (parent_id);

CREATE TABLE IF NOT EXISTS notifications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	user_id INTEGER, 
	level INTEGER NOT NULL, 
	category VARCHAR(30) NOT NULL, 
	title VARCHAR(120) NOT NULL, 
	content VARCHAR(500), 
	link VARCHAR(200), 
	is_read BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_read ON notifications (user_id, is_read, created_at);

CREATE TABLE IF NOT EXISTS permissions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(80) NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	group_name VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_permissions_code" ON permissions (code);

CREATE TABLE IF NOT EXISTS roles (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(50) NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	description VARCHAR(200), 
	is_system BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_roles_code" ON roles (code);

CREATE TABLE IF NOT EXISTS cameras (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	drone_id INTEGER NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	protocol INTEGER NOT NULL, 
	stream_url VARCHAR(500) NOT NULL, 
	description VARCHAR(200), 
	sort_order INTEGER NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(drone_id) REFERENCES drones (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_cameras_drone_id_sort_order" ON cameras (drone_id, sort_order);

CREATE TABLE IF NOT EXISTS charge_sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	drone_id INTEGER NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	ended_at TIMESTAMP WITH TIME ZONE, 
	start_percent NUMERIC(5, 2) NOT NULL, 
	end_percent NUMERIC(5, 2) NOT NULL, 
	energy_wh NUMERIC(10, 2) NOT NULL, 
	duration_seconds INTEGER NOT NULL, 
	station_name VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(drone_id) REFERENCES drones (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_charge_sessions_drone_id_started_at" ON charge_sessions (drone_id, started_at);

CREATE TABLE IF NOT EXISTS drone_telemetry (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	drone_id INTEGER NOT NULL, 
	recorded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	latitude DOUBLE PRECISION NOT NULL, 
	longitude DOUBLE PRECISION NOT NULL, 
	altitude_m DOUBLE PRECISION NOT NULL, 
	speed_mps DOUBLE PRECISION NOT NULL, 
	heading_deg DOUBLE PRECISION NOT NULL, 
	battery_percent NUMERIC(5, 2) NOT NULL, 
	voltage_v NUMERIC(8, 2) NOT NULL, 
	current_a NUMERIC(8, 2) NOT NULL, 
	power_w NUMERIC(8, 2) NOT NULL, 
	satellites INTEGER NOT NULL, 
	signal_percent INTEGER NOT NULL, 
	status INTEGER NOT NULL, 
	work_order_id BIGINT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(drone_id) REFERENCES drones (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_drone_telemetry_drone_recorded ON drone_telemetry (drone_id, recorded_at);

CREATE TABLE IF NOT EXISTS role_permissions (
	role_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	PRIMARY KEY (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_role_permissions_permission_id" ON role_permissions (permission_id);

CREATE TABLE IF NOT EXISTS route_revisions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	route_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	snapshot_json JSONB NOT NULL, 
	change_note VARCHAR(200), 
	created_by INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(route_id) REFERENCES flight_routes (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_route_revisions_route_id_version" ON route_revisions (route_id, version);

CREATE TABLE IF NOT EXISTS route_waypoints (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	route_id INTEGER NOT NULL, 
	map_point_id INTEGER, 
	sequence INTEGER NOT NULL, 
	latitude DOUBLE PRECISION NOT NULL, 
	longitude DOUBLE PRECISION NOT NULL, 
	altitude_m DOUBLE PRECISION NOT NULL, 
	action INTEGER NOT NULL, 
	hover_seconds INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(route_id) REFERENCES flight_routes (id) ON DELETE CASCADE, 
	FOREIGN KEY(map_point_id) REFERENCES map_points (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_route_waypoints_map_point_id" ON route_waypoints (map_point_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_route_waypoints_route_id_sequence" ON route_waypoints (route_id, sequence);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	username VARCHAR(50) NOT NULL, 
	email VARCHAR(120) NOT NULL, 
	display_name VARCHAR(50) NOT NULL, 
	password_hash VARCHAR(200) NOT NULL, 
	role_id INTEGER NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	failed_login_count INTEGER NOT NULL, 
	locked_until TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_email" ON users (email);
CREATE INDEX IF NOT EXISTS "IX_users_role_id" ON users (role_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_username" ON users (username);

CREATE TABLE IF NOT EXISTS work_order_templates (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	name VARCHAR(80) NOT NULL, 
	description VARCHAR(300), 
	default_route_id INTEGER, 
	default_priority INTEGER NOT NULL, 
	estimated_minutes INTEGER NOT NULL, 
	checklist_json JSONB NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(default_route_id) REFERENCES flight_routes (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_work_order_templates_default_route_id" ON work_order_templates (default_route_id);

CREATE TABLE IF NOT EXISTS refresh_tokens (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	user_id INTEGER NOT NULL, 
	token VARCHAR(200) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_refresh_tokens_token" ON refresh_tokens (token);
CREATE INDEX IF NOT EXISTS "IX_refresh_tokens_user_id" ON refresh_tokens (user_id);

CREATE TABLE IF NOT EXISTS work_orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	order_no VARCHAR(30) NOT NULL, 
	title VARCHAR(120) NOT NULL, 
	description VARCHAR(500), 
	template_id INTEGER, 
	route_id INTEGER, 
	drone_id INTEGER, 
	status INTEGER NOT NULL, 
	priority INTEGER NOT NULL, 
	scheduled_at TIMESTAMP WITH TIME ZONE, 
	started_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	duration_seconds INTEGER, 
	energy_used_wh NUMERIC(10, 2), 
	progress_percent INTEGER NOT NULL, 
	assignee_user_id INTEGER, 
	created_by INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	remark VARCHAR(500), 
	PRIMARY KEY (id), 
	FOREIGN KEY(template_id) REFERENCES work_order_templates (id) ON DELETE SET NULL, 
	FOREIGN KEY(route_id) REFERENCES flight_routes (id) ON DELETE SET NULL, 
	FOREIGN KEY(drone_id) REFERENCES drones (id) ON DELETE SET NULL, 
	FOREIGN KEY(assignee_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_work_orders_assignee_user_id" ON work_orders (assignee_user_id);
CREATE INDEX IF NOT EXISTS "IX_work_orders_created_at" ON work_orders (created_at);
CREATE INDEX IF NOT EXISTS "IX_work_orders_drone_id" ON work_orders (drone_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_work_orders_order_no" ON work_orders (order_no);
CREATE INDEX IF NOT EXISTS "IX_work_orders_route_id" ON work_orders (route_id);
CREATE INDEX IF NOT EXISTS "IX_work_orders_status" ON work_orders (status);
CREATE INDEX IF NOT EXISTS "IX_work_orders_template_id" ON work_orders (template_id);

CREATE TABLE IF NOT EXISTS mission_logs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	work_order_id BIGINT, 
	drone_id INTEGER, 
	event_type INTEGER NOT NULL, 
	message VARCHAR(300) NOT NULL, 
	detail_json JSONB, 
	occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(work_order_id) REFERENCES work_orders (id) ON DELETE CASCADE, 
	FOREIGN KEY(drone_id) REFERENCES drones (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_mission_logs_drone_id" ON mission_logs (drone_id);
CREATE INDEX IF NOT EXISTS "IX_mission_logs_occurred_at" ON mission_logs (occurred_at);
CREATE INDEX IF NOT EXISTS "IX_mission_logs_work_order_id" ON mission_logs (work_order_id);

COMMIT;
